### ISSUE TITLE
Encoding Issues with chart.toByteArray() and German Umlauts

### ISSUE THREAD

**Issue by mirkofetter** [typpo/quickchart-java#2]
When i use the JAva client, to generate a chart as byte array with German Umlauts (ä,ö,ü, and also ß) the graphhic has wrong glyphs in it. When I print the URL of the same chart with chart.getUrl() and copy it into the browser, i have no issues. Is it possible to change the Encoding of the HTTP request the client uses?

**Comment by typpo** [comment]
Thanks for the report! I have a fix in and will close this issue once v1.1.1 is published.

**Comment by typpo** [comment]
Fixed by #3 and published as version 1.1.1
