### ISSUE TITLE
This project uses an obsolete http.url lib to build url

### ISSUE THREAD

**Issue by g39088902** [typpo/quickchart-java#4]
This project uses an obsolete http.url lib to build url, and it cant run under API29+Kotlin. I write a Kotlin version url builder by myself to solve this problem.

**Comment by megoRU** [comment]
I can rewrite and send a pull request. What library is needed?

**Comment by g39088902** [comment]
Thanks for the reply, but I've stopped working on the relate project, so I can close this issue now.
